// Imports removed

export const WHATSAPP_NUMBER = "+918799445757"; // Replace with actual business number

export const DICTIONARY = {
  // Navigation
  "nav.home": { EN: "Home", GU: "ઘર", HI: "होम" },
  "nav.services": { EN: "Services", GU: "સેવાઓ", HI: "सेवाएं" },
  "nav.apply": { EN: "Apply Now", GU: "અરજી કરો", HI: "आवेदन करें" },
  "nav.contact": { EN: "Contact", GU: "સંપર્ક", HI: "संपर्क" },

  // Hero
  "hero.title": {
    EN: "Your Trusted Partner for Government Services",
    GU: "સરકારી સેવાઓ માટે આપનો વિશ્વાસુ સાથી",
    HI: "सरकारी सेवाओं के लिए आपका विश्वसनीय साथी",
  },
  "hero.subtitle": {
    EN: "We simplify the process of getting certificates, licenses, and legal documents. Fast, secure, and hassle-free.",
    GU: "અમે પ્રમાણપત્રો, લાઇસન્સ અને કાનૂની દસ્તાવેજો મેળવવાની પ્રક્રિયાને સરળ બનાવીએ છીએ. ઝડપી, સુરક્ષિત અને મુશ્કેલી-મુક્ત.",
    HI: "हम प्रमाण पत्र, लाइसेंस और कानूनी दस्तावेज प्राप्त करने की प्रक्रिया को सरल बनाते हैं। तेज, सुरक्षित और परेशानी मुक्त।",
  },
  "hero.cta": { EN: "Get Started", GU: "શરૂ કરો", HI: "शुरू करें" },
  "hero.secondary_cta": {
    EN: "View Services",
    GU: "સેવાઓ જુઓ",
    HI: "सेवाएं देखें",
  },

  // Sections
  "section.why_choose_us": {
    EN: "Why Choose Us?",
    GU: "અમને શા માટે પસંદ કરશો?",
    HI: "हमें क्यों चुनें?",
  },
  "section.our_services": {
    EN: "Our Services",
    GU: "અમારી સેવાઓ",
    HI: "हमारी सेवाएं",
  },
  "section.testimonials": {
    EN: "What Our Clients Say",
    GU: "અમારા ગ્રાહકો શું કહે છે",
    HI: "हमारे ग्राहक क्या कहते हैं",
  },
  "section.stats": { EN: "Our Impact", GU: "અમારો પ્રભાવ", HI: "हमारा प्रभाव" },
  "section.contact": {
    EN: "Get in Touch",
    GU: "સંપર્ક કરો",
    HI: "संपर्क करें",
  },

  // Categories
  "category.CERTIFICATE": {
    EN: "Certificate",
    GU: "પ્રમાણપત્ર",
    HI: "प्रमाण पत्र",
  },
  "category.ASSISTANCE": { EN: "Assistance", GU: "સહાય", HI: "ASSISTANCE" },
  "category.ONLINE": { EN: "Online", GU: "ઓનલાઇન", HI: "ऑनलाइन" },
  "category.OTHER": { EN: "Other", GU: "અન્ય", HI: "अन्य" },

  // Why Choose Us
  "wcu.fast_title": {
    EN: "Fast Processing",
    GU: "ઝડપી પ્રક્રિયા",
    HI: "तेजी से प्रसंस्करण",
  },
  "wcu.fast_desc": {
    EN: "We prioritize your time and ensure quick turnarounds.",
    GU: "અમે તમારા સમયને મહત્વ આપીએ છીએ અને ઝડપી સેવા સુનિશ્ચિત કરીએ છીએ.",
    HI: "हम आपके समय को प्राथमिकता देते हैं और त्वरित बदलाव सुनिश्चित करते हैं।",
  },
  "wcu.expert_title": {
    EN: "Expert Guidance",
    GU: "નિષ્ણાત માર્ગદર્શન",
    HI: "विशेषज्ञ मार्गदर्शन",
  },
  "wcu.expert_desc": {
    EN: "Our team knows the ins and outs of government paperwork.",
    GU: "અમારી ટીમ સરકારી દસ્તાવેજોની તમામ બારીકાઈઓ જાણે છે.",
    HI: "हमारी टीम सरकारी कागजी कार्रवाई की बारीकियों को जानती है।",
  },
  "wcu.secure_title": {
    EN: "100% Secure",
    GU: "૧૦૦% સુરક્ષિત",
    HI: "१००% सुरक्षित",
  },
  "wcu.secure_desc": {
    EN: "Your documents and data are safe with us.",
    GU: "તમારા દસ્તાવેજો અને ડેટા અમારી સાથે સુરક્ષિત છે.",
    HI: "आपके दस्तावेज़ और डेटा हमारे पास सुरक्षित हैं।",
  },

  // Apply Page
  "apply.title": {
    EN: "Apply for a Service",
    GU: "સેવા માટે અરજી કરો",
    HI: "सेवा के लिए आवेदन करें",
  },
  "apply.subtitle": {
    EN: "Fill out the form below and we will contact you on WhatsApp immediately.",
    GU: "નીચે આપેલ ફોર્મ ભરો અને અમે તરત જ WhatsApp પર તમારો સંપર્ક કરીશું.",
    HI: "नीचे दिया गया फॉर्म भरें और हम तुरंत व्हाट्सएप पर आपसे संपर्क करेंगे।",
  },
  "form.name": { EN: "Full Name", GU: "પૂરું નામ", HI: "पूरा नाम" },
  "form.phone": { EN: "Phone Number", GU: "ફોન નંબર", HI: "फ़ोन नंबर" },
  "form.service": {
    EN: "Select Service",
    GU: "સેવા પસંદ કરો",
    HI: "सेवा चुनें",
  },
  "form.message": {
    EN: "Additional Message (Optional)",
    GU: "વધારાનો સંદેશ (વૈકલ્પિક)",
    HI: "अतिरिक्त संदेश (वैकल्पिक)",
  },
  "form.submit": {
    EN: "Submit Application",
    GU: "અરજી સબમિટ કરો",
    HI: "आवेदन जमा करें",
  },

  // Footer
  "footer.desc": {
    EN: "Simplifying government documentation for everyone.",
    GU: "દરેક માટે સરકારી દસ્તાવેજીકરણ સરળ બનાવવું.",
    HI: "सभी के लिए सरकारी दस्तावेज़ीकरण को सरल बनाना।",
  },
  "footer.quick_links": {
    EN: "Quick Links",
    GU: "ઝડપી લિંક્સ",
    HI: "त्वरित लिंक",
  },
  "footer.contact_info": {
    EN: "Contact Info",
    GU: "સંપર્ક માહિતી",
    HI: "संपर्क जानकारी",
  },
  "footer.rights": {
    EN: "All Rights Reserved",
    GU: "સર્વાધિકાર સુરક્ષિત",
    HI: "सभी अधिकार सुरक्षित",
  },

  // Common
  "btn.learn_more": { EN: "Learn More", GU: "વધુ જાણો", HI: "अधिक जानें" },
  "btn.apply_now": { EN: "Apply Now", GU: "અરજી કરો", HI: "आवेदन करें" },

  // Admin Profile
  "admin.profile": {
    EN: "Admin Profile",
    GU: "વ્યવસ્થાપક પ્રોફાઇલ",
    HI: "व्यवस्थापक प्रोफाइल",
  },
  "admin.profile_picture": {
    EN: "Profile Picture",
    GU: "પ્રોફાઇલ ચિત્ર",
    HI: "प्रोफाइल चित्र",
  },
  "admin.upload_picture": {
    EN: "Upload New Picture",
    GU: "નવું ચિત્ર અપલોડ કરો",
    HI: "नई तस्वीर अपलोड करें",
  },
  "admin.save_changes": {
    EN: "Save Changes",
    GU: "બદલાવો સાચવો",
    HI: "परिवर्तन सहेजें",
  },
  "admin.cancel": { EN: "Cancel", GU: "રદ કરો", HI: "रद्द करें" },
  "admin.profile_updated": {
    EN: "Profile updated successfully!",
    GU: "પ્રોફાઇલ સફળતાથી અપડેટ થયું!",
    HI: "प्रोफाइल सफलतापूर्वक अपडेट हो गया!",
  },

  // Admin Services
  "admin.service_management": {
    EN: "Service Management",
    GU: "સેવા વ્યવસ્થાપન",
    HI: "सेवा प्रबंधन",
  },
  "admin.apply_services_desc": {
    EN: "Apply for services on behalf of customers",
    GU: "ગ્રાહકોની તરફથી સેવાઓ માટે અરજી કરો",
    HI: "ग्राहकों की ओर से सेवाओं के लिए आवेदन करें",
  },
  "admin.search_services": {
    EN: "Search services...",
    GU: "સેવાઓ શોધો...",
    HI: "सेवाओं को खोजें...",
  },
  "admin.apply_for_user": {
    EN: "Apply for User",
    GU: "વપરાશકર્તા માટે અરજી કરો",
    HI: "उपयोगकर्ता के लिए आवेदन करें",
  },
  "admin.no_services_found": {
    EN: "No services found matching your search.",
    GU: "તમારી શોધ સાથે મેળતી સેવાઓ નથી.",
    HI: "आपकी खोज से मेल खाने वाली कोई सेवा नहीं मिली।",
  },
  "admin.new_application": {
    EN: "New Application",
    GU: "નવો અરજી",
    HI: "नया आवेदन",
  },
  "admin.applying_for": {
    EN: "Applying for:",
    GU: "માટે અરજી કરી રહ્યા છો:",
    HI: "के लिए आवेदन कर रहे हैं:",
  },
  "admin.enter_customer_name": {
    EN: "Enter customer name",
    GU: "ગ્રાહક નું નામ દર્ક કરો",
    HI: "ग्राहक का नाम दर्ज करें",
  },
  "admin.whatsapp_number": {
    EN: "WhatsApp Number",
    GU: "વ્હોટ્સએપ નંબર",
    HI: "व्हाट्सएप नंबर",
  },
  "admin.submit_application": {
    EN: "Submit Application",
    GU: "અરજી સમર્પણ કરો",
    HI: "आवेदन जमा करें",
  },
};

// services data
export const SERVICES_DATA = [
  //certificate services
  {
    id: "ews-reservation-cert",
    iconName: "FileText",
    category: "CERTIFICATE",
    title: {
      EN: "10% EWS Reservation Certificate",
      GU: "૧૦% (EWS) અનામત વર્ગનો દાખલો",
      HI: "10% ईडब्ल्यूएस आरक्षण प्रमाण पत्र",
    },
    description: {
      EN: "Certificate for 10% Economically Weaker Section (EWS) reservation category.",
      GU: "૧૦% આર્થિક રીતે નબળા વર્ગ (EWS) અનામત માટેનો દાખલો.",
      HI: "10% आर्थिक रूप से कमजोर वर्ग (EWS) आरक्षण हेतु प्रमाण पत्र।",
    },
    documents: {
      EN: [
        "1 photo of applicant and 1 photo of father",
        "Aadhaar Card and Voter ID (of applicant and father)",
        "Applicant's Leaving Certificate or Bonafide Certificate",
        "Leaving Certificate of applicant's father / uncle / aunt (any one)",
        "Income Certificate",
        "Ration Card",
        "Electricity Bill",
        "Property Tax Bill",
        "If agricultural income: 7/12 and 8A extract of father",
      ],
      GU: [
        "અરજદાર નો (૧) ફોટો અને પિતા નો (૧) ફોટો",
        "આધાર કાર્ડ અને ચુંટણી કાર્ડ (અરજદાર અને તેના પિતા નુ)",
        "અરજદાર નું લીવિંગ સર્ટી અથવા બોનાફાઇડ",
        "અરજદાર ના પિતા / કાકા / ફોઈ નું લિવિંગ સર્ટી (કોઈ એક)",
        "આવક નો દાખલો",
        "રેશન કાર્ડ",
        "લાઇટબીલ",
        "વેરાબીલ",
        "ખેતી ની આવક હોય તો પિતાના ૭/૧૨ અને ૮અ ની નકલ",
      ],
      HI: [
        "1 फोटो आवेदक का और 1 फोटो उसके पिता का",
        "आधार कार्ड और वोटर आईडी (आवेदक और उसके पिता का)",
        "आवेदक का लिविंग सर्टिफिकेट या बोनाफाइड सर्टिफिकेट",
        "आवेदक के पिता / काका / बुआ में से किसी एक का लिविंग सर्टिफिकेट",
        "आय प्रमाण पत्र",
        "राशन कार्ड",
        "बिजली बिल",
        "प्रॉपर्टी टैक्स बिल",
        "यदि कृषि आय हो तो पिता की 7/12 और 8A नकल",
      ],
    },
  },

  {
    id: "income-cert",
    iconName: "FileText",
    category: "CERTIFICATE",
    title: {
      EN: "Income Certificate",
      GU: "આવકનો દાખલો",
      HI: "आय प्रमाण पत्र",
    },
    description: {
      EN: "Proof of annual income for government purposes, schemes, and applications.",
      GU: "સરકારી કામકાજ, યોજનાઓ અને અરજી માટે વાર્ષિક આવકનો પુરાવો.",
      HI: "सरकारी कार्यों, योजनाओं और आवेदनों के लिए वार्षिक आय का प्रमाण।",
    },
    documents: {
      EN: [
        "1 photo of applicant",
        "Aadhaar Card (of applicant and sons whose names are on Ration Card)",
        "Voter ID Card",
        "Ration Card",
        "Electricity Bill",
        "Property Tax Bill",
      ],
      GU: [
        "અરજદાર નો (૧) ફોટો",
        "આધાર કાર્ડ (અરજદાર અને રેશન કાર્ડ માં નામ હોય તે પુત્ર ના)",
        "ચુંટણી કાર્ડ",
        "રેશન કાર્ડ",
        "લાઇટબીલ",
        "વેરાબીલ",
      ],
      HI: [
        "आवेदक का 1 फोटो",
        "आधार कार्ड (आवेदक का और राशन कार्ड में नाम वाले पुत्र का)",
        "वोटर आईडी कार्ड",
        "राशन कार्ड",
        "बिजली बिल",
        "प्रॉपर्टी टैक्स बिल",
      ],
    },
  },

  {
    id: "trademark-copyright-registered-mark",
    iconName: "FileText",
    category: "OTHER",
    title: {
      EN: "Trademark / Copyright / Registered Mark",
      GU: "ટ્રેડમાર્ક / કૉપિરાઇટ / રજિસ્ટર્ડ માર્ક",
      HI: "ट्रेडमार्क / कॉपीराइट / रजिस्टर्ड मार्क",
    },
    description: {
      EN: "Documents required for applying for Trademark, Copyright, or Registered Mark.",
      GU: "ટ્રેડમાર્ક, કૉપિરાઇટ અથવા રજિસ્ટર્ડ માર્ક માટે અરજી કરવા જરૂરી દસ્તાવેજો.",
      HI: "ट्रेडमार्क, कॉपीराइट या रजिस्टर्ड मार्क के आवेदन हेतु आवश्यक दस्तावेज़।",
    },
    documents: {
      EN: [
        "Scanned copy of the logo",
        "Properly signed Form-48",
        "Udyam Registration Certificate",
        "Partnership Deed or Incorporation Certificate",
        "ID proof of the signatory/applicant",
        "Address proof of the signatory/applicant",
      ],
      GU: [
        "લોગોની સ્કેન કરેલી નકલ",
        "યોગ્ય રીતે સહી કરેલ ફોર્મ-48",
        "ઉદ્યોગ નોંધણી પ્રમાણપત્ર",
        "ભાગીદારી દસ્તાવેજ અથવા નિગમ પ્રમાણપત્ર",
        "સહી કરનાર/અરજદારના ઓળખ પુરાવાની નકલ",
        "સહી કરનાર/અરજદારના સરનામાના પુરાવાની નકલ",
      ],
      HI: [
        "लोगो की स्कैन की हुई प्रति",
        "सही तरीके से हस्ताक्षरित फॉर्म-48",
        "उद्योग आधार / उद्यम पंजीकरण प्रमाण पत्र",
        "पार्टनरशिप डीड या निगम पंजीकरण प्रमाण पत्र",
        "हस्ताक्षरकर्ता/आवेदक का पहचान प्रमाण",
        "हस्ताक्षरकर्ता/आवेदक का पता प्रमाण",
      ],
    },
  },

  {
    id: "unreserved-category-cert",
    iconName: "FileText",
    category: "CERTIFICATE",
    title: {
      EN: "non-reserved Category Certificate",
      GU: "બિનઅનામત વર્ગનો દાખલો",
      HI: "अनारक्षित वर्ग प्रमाण पत्र",
    },
    description: {
      EN: "Certificate for applicants belonging to the unreserved category.",
      GU: "બિનઅનામત વર્ગમાં આવનારા અરજદારો માટેનો દાખલો.",
      HI: "अनारक्षित वर्ग से संबंधित आवेदकों के लिए प्रमाण पत्र।",
    },
    documents: {
      EN: [
        "1 photo of applicant",
        "Aadhaar Card (of applicant and father)",
        "Applicant's Leaving Certificate or Bonafide Certificate",
        "Leaving Certificate of applicant's father / uncle / aunt (any one)",
        "Ration Card",
        "Electricity Bill",
        "Property Tax Bill",
      ],
      GU: [
        "અરજદાર નો (૧) ફોટો",
        "આધાર કાર્ડ (અરજદાર અને તેના પિતા નુ)",
        "અરજદાર નું લીવિંગ સર્ટી અથવા બોનાફાઇડ",
        "અરજદાર ના પિતા / કાકા / ફોઈ નું લિવિંગ સર્ટી (કોઈ એક)",
        "રેશન કાર્ડ",
        "લાઇટબીલ",
        "વેરાબીલ",
      ],
      HI: [
        "आवेदक का 1 फोटो",
        "आधार कार्ड (आवेदक और उसके पिता का)",
        "आवेदक का लिविंग सर्टिफिकेट या बोनाफाइड सर्टिफिकेट",
        "आवेदक के पिता / काका / बुआ में से किसी एक का लिविंग सर्टिफिकेट",
        "राशन कार्ड",
        "बिजली बिल",
        "प्रॉपर्टी टैक्स बिल",
      ],
    },
  },
  {
    id: "domicile-cert",
    iconName: "FileText",
    category: "CERTIFICATE",
    title: {
      EN: "Domicile Certificate",
      GU: "ડોમીસાઈલ સર્ટિફિકેટ",
      HI: "डोमिसाइल प्रमाण पत्र",
    },
    description: {
      EN: "Certificate proving permanent residence in the state.",
      GU: "રાજ્યમાં કાયમી રહેઠાણ દર્શાવતું ડોમીસાઈલ પ્રમાણપત્ર.",
      HI: "राज्य में स्थायी निवास सिद्ध करने वाला प्रमाण पत्र।",
    },
    documents: {
      EN: [
        "1 photo of applicant and 1 photo of father",
        "Aadhaar Card and Voter ID (of applicant and father)",
        "Applicant's Leaving Certificate or Bonafide Certificate",
        "Birth Certificate of applicant",
        "Leaving Certificate of father / uncle / aunt (any one)",
        "All mark sheets from Std. 1 onwards",
        "Income Certificate",
        "Ration Card",
        "Electricity Bill",
        "Property Tax Bill",
        "Police Station Certificate",
        "Talati's 10-year residence certificate",
        "Affidavit",
      ],
      GU: [
        "અરજદાર નો (૧) ફોટો અને પિતા નો (૧) ફોટો",
        "આધાર કાર્ડ અને ચુંટણી કાર્ડ (અરજદાર અને તેના પિતા નુ)",
        "અરજદાર નું લીવિંગ સર્ટી અથવા બોનાફાઇડ",
        "અરજદાર નો જન્મ નો દાખલો",
        "અરજદાર ના પિતા / કાકા / ફોઈ નું લિવિંગ સર્ટી (કોઈ એક)",
        "ધોરણ ૧ થી તમામ અભ્યાસ ની માર્કશીટ",
        "આવક નો દાખલો",
        "રેશન કાર્ડ",
        "લાઇટબીલ",
        "વેરાબીલ",
        "પોલીસ સ્ટેશન નો દાખલો",
        "તલાટીશ્રી નો ૧૦ વર્ષ નો રહેણાક નો દાખલો",
        "સોગંદનામું",
      ],
      HI: [
        "आवेदक का 1 फोटो और पिता का 1 फोटो",
        "आधार कार्ड और वोटर आईडी (आवेदक और पिता का)",
        "आवेदक का लिविंग सर्टिफिकेट या बोनाफाइड सर्टिफिकेट",
        "आवेदक का जन्म प्रमाण पत्र",
        "आवेदक के पिता / काका / बुआ में से किसी एक का लिविंग सर्टिफिकेट",
        "कक्षा 1 से अब तक की सभी मार्कशीट",
        "आय प्रमाण पत्र",
        "राशन कार्ड",
        "बिजली बिल",
        "प्रॉपर्टी टैक्स बिल",
        "पुलिस स्टेशन से प्रमाण पत्र",
        "तलाटी द्वारा 10 वर्ष का निवास प्रमाण पत्र",
        "शपथ पत्र (एफिडेविट)",
      ],
    },
  },
  {
    id: "food-license",
    iconName: "FileText",
    category: "ONLINE",
    title: {
      EN: "Food License",
      GU: "ફૂડ લાયસન્સ",
      HI: "फूड लाइसेंस",
    },
    description: {
      EN: "License for running a food-related business or establishment.",
      GU: "ખાદ્ય સંબંધિત ધંધો ચલાવવા માટેનું ફૂડ લાયસન્સ.",
      HI: "खाद्य संबंधित व्यवसाय चलाने के लिए आवश्यक लाइसेंस।",
    },
    documents: {
      EN: [
        "Aadhaar Card",
        "PAN Card",
        "Rent Agreement (if place is rented)",
        "Consent Letter (if owned premises)",
        "Business name and address details",
        "Health NOC",
        "Electricity Bill",
        "Property Tax Bill",
        "Mobile Number",
        "Email ID",
        "Photos of business premises with machinery",
      ],
      GU: [
        "આધાર કાર્ડ",
        "પાન કાર્ડ",
        "ભાડા ની જગ્યા હોય તો ભાડા કરાર",
        "માલિકી ની જગ્યા હોય તો સંમતિ પત્રક",
        "ધંધા નુ નામ સરનામું",
        "હેલ્થ NOC",
        "લાઈટ બીલ",
        "વેરા બીલ",
        "મોબાઈલ નંબર",
        "ઈ મેઈલ ID",
        "ધંધા ના સ્થળ ના ફોટા મશીનરી સાથે ના",
      ],
      HI: [
        "आधार कार्ड",
        "पैन कार्ड",
        "यदि जगह किराये की हो तो रेंट एग्रीमेंट",
        "यदि जगह स्वयं की हो तो सहमति पत्र",
        "व्यवसाय का नाम और पता विवरण",
        "हेल्थ NOC",
        "बिजली बिल",
        "प्रॉपर्टी टैक्स बिल",
        "मोबाइल नंबर",
        "ईमेल आईडी",
        "मशीनरी सहित दुकान / व्यवसाय स्थल के फोटो",
      ],
    },
  },
  {
    id: "itr-income-tax-return",
    iconName: "FileText",
    category: "OTHER",
    title: {
      EN: "ITR (Income Tax Return) ",
      GU: "I.T.R ઇન્કમટેક્ષ રિટર્ન ",
      HI: "आईटीआर (आयकर रिटर्न) दस्तावेज़",
    },
    description: {
      EN: "Required documents for filing Income Tax Return (ITR).",
      GU: "ઇન્કમટેક્ષ રિટર્ન (ITR) ભરવા માટે જરૂરી પુરાવા.",
      HI: "आयकर रिटर्न (ITR) भरने के लिए आवश्यक दस्तावेज़।",
    },
    documents: {
      EN: [
        "PAN Card",
        "Aadhaar Card",
        "Bank Passbook with 1-year statement for all banks (from 01/04 to 31/03)",
        "LIC premium receipts (if any)",
        "FD receipts (if any)",
        "Children's school fee receipts (if any)",
        "Loan statement (if any loan is running)",
        "Details of any property purchase or sale",
        "Details of any other investments or income",
        "7/12 extract if agricultural income",
        "Purchase / sale bills of agricultural produce (if agricultural income)",
        "Form 16 (if salaried)",
        "Purchase / sale and expense bills (if business income)",
      ],
      GU: [
        "પાન કાર્ડ",
        "આધાર કાર્ડ",
        "બેન્ક પાસબૂક ૧ વર્ષ ની એન્ટ્રી સાથે (બધી બેન્ક ની ૦૧/૦૪ થી ૩૧/૦૩ સુધીની)",
        "L.I.C. ની રસીદ ની નકલ (હોય તો)",
        "F.D. ની રસીદ ની નકલ (હોય તો)",
        "બાળકોની સ્કૂલ ફી ની રસીદ (હોય તો)",
        "કોઈ લોન ચાલતી હોય તો તેનું સ્ટેટમેન્ટ",
        "કોઈ પ્રોપર્ટી ખરીદી કે વેચાણ કરેલ હોય તો તેની વિગત",
        "અન્ય કોઈ રોકાણ કે આવક હોય તો તેની વિગત",
        "ખેતી ની આવક હોય તો ૭/૧૨ ની નકલ",
        "ખેતી વાળી ના ખરીદ વેચાણ ના બીલ (ખેતી ની આવક હોય તો)",
        "નોકરી કરતા હોય તેવામાં ફોર્મ–૧૬",
        "ધંધા ની આવક હોય તો ખરીદ/વેચાણ તથા ખર્ચ ના બીલ",
      ],
      HI: [
        "पैन कार्ड",
        "आधार कार्ड",
        "सभी बैंकों की पासबुक और 1 वर्ष का स्टेटमेंट (01/04 से 31/03 तक)",
        "एल.आई.सी. प्रीमियम रसीद की कॉपी (यदि हो)",
        "एफ.डी. रसीद की कॉपी (यदि हो)",
        "बच्चों की स्कूल फीस की रसीद (यदि हो)",
        "यदि कोई लोन चल रहा हो तो उसका स्टेटमेंट",
        "यदि कोई प्रॉपर्टी खरीदी या बेची हो तो उसका विवरण",
        "अन्य कोई निवेश या आय हो तो उसका विवरण",
        "यदि कृषि आय हो तो 7/12 की नकल",
        "कृषि उपज की खरीद–बिक्री के बिल (यदि कृषि आय हो)",
        "यदि नौकरी करते हों तो फॉर्म–16",
        "यदि व्यवसाय आय हो तो खरीद/बिक्री व खर्च के बिल",
      ],
    },
  },
  {
    id: "caste-cert",
    iconName: "FileText",
    category: "CERTIFICATE",
    title: {
      EN: "Caste Certificate",
      GU: "જાતિનો દાખલો",
      HI: "जाति प्रमाण पत्र",
    },
    description: {
      EN: "Certificate confirming the applicant's caste or community.",
      GU: "અરજદારની જાતિ/સમુદાયની પુષ્ટિ કરતી પ્રમાણપત્ર.",
      HI: "आवेदक की जाति/समुदाय प्रमाणित करने वाला दस्तावेज़।",
    },
    documents: {
      EN: [
        "1 photo of applicant and 1 photo of father",
        "Aadhaar Card and Voter ID (of applicant and father)",
        "Applicant's Leaving Certificate or Bonafide Certificate",
        "Leaving Certificate of applicant's father / uncle / aunt (any one)",
        "Ration Card",
        "Electricity Bill",
        "Property Tax Bill",
      ],
      GU: [
        "અરજદાર નો (૧) ફોટો અને પિતા નો (૧) ફોટો",
        "આધાર કાર્ડ અને ચુટણી કાર્ડ (અરજદાર અને તેના પિતા નુ)",
        "અરજદાર નું લીવિંગ સર્ટી અથવા બોનાફાઇડ",
        "અરજદાર ના પિતા / કાકા / ફોઈ નું લિવિંગ સર્ટી (કોઈ એક)",
        "રેશન કાર્ડ",
        "લાઇટબીલ",
        "વેરાબીલ",
      ],
      HI: [
        "आवेदक का 1 फोटो और उसके पिता का 1 फोटो",
        "आधार कार्ड और वोटर आईडी (आवेदक और उसके पिता का)",
        "आवेदक का लिविंग सर्टिफिकेट या बोनाफाइड सर्टिफिकेट",
        "आवेदक के पिता / काका / बुआ का लिविंग सर्टिफिकेट (किसी एक का)",
        "राशन कार्ड",
        "बिजली बिल",
        "प्रॉपर्टी टैक्स बिल",
      ],
    },
  },
  {
    id: "kuvarbai-mamera-scheme",
    iconName: "FileText",
    category: "ASSISTANCE",
    title: {
      EN: "Kuvarbai Mamera Scheme",
      GU: "કુવરબાઈ મામેરા યોજના",
      HI: "कुंवरबाई मामेरा योजना",
    },
    description: {
      EN: "Documents required for Kuvarbai Mamera assistance scheme for daughters.",
      GU: "કન્યાઓ માટેની કુવરબાઈ મામેરા સહાય યોજના માટે જરૂરી દસ્તાવેજો.",
      HI: "कन्याओं के लिए कुंवरबाई मामेरा सहायता योजना हेतु आवश्यक दस्तावेज़।",
    },
    documents: {
      EN: [
        "1 photo of the bride (daughter)",
        "Aadhaar Card of daughter",
        "Aadhaar Card of daughter's father",
        "Aadhaar Card of husband",
        "Income Certificate of daughter's father",
        "Bank Passbook of daughter",
        "Marriage Certificate",
        "Ration Card with daughter's name and KYC completed",
        "Note: Form must be filled within 2 years of marriage",
      ],
      GU: [
        "૧ ફોટો કન્યા નો",
        "આધાર કાર્ડ કન્યાનું",
        "આધાર કાર્ડ કન્યાના પિતાનું",
        "આધાર કાર્ડ પતિનું",
        "આવક નો દાખલો કન્યાના પિતા નો",
        "બેંક પાસબૂક કન્યાની",
        "મેરેજ સર્ટી",
        "રેશનકાર્ડ કન્યાના નામ વાળુ (KYC ફરજીયાત)",
        "નોંધ: લગ્ન ના ૨ વર્ષ ની સમય મર્યાદામાં ફોર્મ ભરવાનું રહેશે.",
      ],
      HI: [
        "1 फोटो कन्या (दुल्हन) का",
        "कन्या का आधार कार्ड",
        "कन्या के पिता का आधार कार्ड",
        "पति का आधार कार्ड",
        "कन्या के पिता का आय प्रमाण पत्र",
        "कन्या की बैंक पासबुक",
        "विवाह प्रमाण पत्र",
        "कन्या के नाम वाला राशन कार्ड (KYC अनिवार्य)",
        "नोट: विवाह की तिथि से 2 वर्ष की अवधि में फॉर्म भरना अनिवार्य है।",
      ],
    },
  },
  {
    id: "marriage-certificate",
    iconName: "FileText",
    category: "CERTIFICATE",
    title: {
      EN: "Marriage Certificate",
      GU: "લગ્ન નોંધ પ્રમાણપત્ર",
      HI: "विवाह प्रमाण पत्र",
    },
    description: {
      EN: "Certificate for registration and proof of marriage.",
      GU: "લગ્ન નોંધી તેની કાનૂની પુરવાર માટેનું પ્રમાણપત્ર.",
      HI: "विवाह के पंजीकरण और कानूनी प्रमाण हेतु प्रमाण पत्र।",
    },
    documents: {
      EN: [
        "Leaving Certificate of groom and bride",
        "Aadhaar Card of groom and bride",
        "Ration Card of groom and bride",
        "Aadhaar Cards of parents of groom and bride",
        "Aadhaar Card of mediator (Gor)",
        "Aadhaar Cards of two witnesses",
        "Wedding invitation card",
        "Joint marriage photos (4x6 size) of wedding rituals",
        "Note: If marriage took place in a village, submit 2 copies of every document",
      ],
      GU: [
        "લીવિંગ સર્ટી (વર તથા કન્યા ના)",
        "આધાર કાર્ડ (વર તથા કન્યા ના)",
        "રેશન કાર્ડ (વર તથા કન્યા ના)",
        "વર તથા કન્યા ના માતા પિતા ના આધાર કાર્ડ",
        "ગોર અદાનું આધાર કાર્ડ",
        "બે સાક્ષી ના આધાર કાર્ડ",
        "લગ્ન કંકોત્રી",
        "લગ્ન ના જોઈટ ફોટા લગ્ન વિધિ વખતના ૪ x ૬ ની સાઈઝ માં",
        "નોંધ: લગ્ન સ્થળ ગામડા માં હોય તો દરેક પુરાવાની ૨ નકલ આપવી.",
      ],
      HI: [
        "वर और वधू के लिविंग सर्टिफिकेट",
        "वर और वधू के आधार कार्ड",
        "वर और वधू के राशन कार्ड",
        "वर तथा वधू के माता–पिता के आधार कार्ड",
        "गोर / मध्यस्थ का आधार कार्ड",
        "दो गवाहों के आधार कार्ड",
        "विवाह का निमंत्रण पत्र",
        "विवाह विधि के समय के जॉइंट फोटो (4 x 6 साइज)",
        "नोट: यदि विवाह गाँव में हुआ हो तो हर दस्तावेज़ की 2 प्रतियाँ देनी होगी।",
      ],
    },
  },
  {
    id: "non-creamy-layer-cert",
    iconName: "FileText",
    category: "CERTIFICATE",
    title: {
      EN: "Non-Creamy Layer Certificate",
      GU: "નોન ક્રિમીલેયર સર્ટિફિકેટ",
      HI: "नॉन क्रीमी लेयर प्रमाण पत्र",
    },
    description: {
      EN: "Non-Creamy Layer certificate for reserved category benefits.",
      GU: "અનામત વર્ગ માટે નોન ક્રિમીલેયર પ્રમાણપત્ર.",
      HI: "आरक्षित वर्ग के लिए नॉन क्रीमी लेयर प्रमाण पत्र।",
    },
    documents: {
      EN: [
        "1 photo of applicant and 1 photo of father",
        "Aadhaar Card and Voter ID (of applicant and father)",
        "Applicant's Leaving Certificate or Bonafide Certificate",
        "Leaving Certificate of applicant's father / uncle / aunt (any one)",
        "Income Certificate",
        "Ration Card",
        "Electricity Bill",
        "Property Tax Bill",
        "Applicant's caste certificate of social and educational category",
        "Affidavit in father's name attached with application",
        "PAN Card",
      ],
      GU: [
        "અરજદાર નો (૧) ફોટો અને પિતા નો (૧) ફોટો",
        "આધાર કાર્ડ અને ચુટણી કાર્ડ (અરજદાર અને તેના પિતા નુ)",
        "અરજદાર નું લીવિંગ સર્ટી અથવા બોનાફાઇડ",
        "અરજદાર ના પિતા / કાકા / ફોઈ નું લિવિંગ સર્ટી (કોઈ એક)",
        "આવક નો દાખલો",
        "રેશન કાર્ડ",
        "લાઇટબીલ",
        "વેરાબીલ",
        "અરજદાર નો સામાજિક અને શૈક્ષણિક વર્ગનો જાતી દાખલો",
        "પિતાના નામ નું અરજી સાથે સોગંદનામું",
        "પાન કાર્ડ",
      ],
      HI: [
        "आवेदक का 1 फोटो और पिता का 1 फोटो",
        "आधार कार्ड और वोटर आईडी (आवेदक और पिता का)",
        "आवेदक का लिविंग सर्टिफिकेट या बोनाफाइड सर्टिफिकेट",
        "आवेदक के पिता / काका / बुआ का लिविंग सर्टिफिकेट (किसी एक का)",
        "आय प्रमाण पत्र",
        "राशन कार्ड",
        "बिजली बिल",
        "प्रॉपर्टी टैक्स बिल",
        "आवेदक की सामाजिक व शैक्षणिक वर्ग की जाति का प्रमाण पत्र",
        "पिता के नाम का शपथ पत्र (आवेदन के साथ)",
        "पैन कार्ड",
      ],
    },
  },
  {
    id: "pan-card",
    iconName: "FileText",
    category: "OTHER",
    title: {
      EN: "PAN Card",
      GU: "પાન કાર્ડ",
      HI: "पैन कार्ड",
    },
    description: {
      EN: "Permanent Account Number (PAN) card documents.",
      GU: "પાન કાર્ડ માટે જરૂરી દસ્તાવેજો.",
      HI: "पैन कार्ड हेतु आवश्यक दस्तावेज़।",
    },
    documents: {
      EN: [
        "2 photos",
        "Aadhaar Card",
        "Father's full name",
        "Mobile Number",
        "Email ID",
      ],
      GU: [
        "૨ ફોટો",
        "આધાર કાર્ડ",
        "પિતાનું આખું નામ",
        "મોબાઈલ નંબર",
        "ઈ મેઈલ ID",
      ],
      HI: [
        "2 फोटो",
        "आधार कार्ड",
        "पिता का पूरा नाम",
        "मोबाइल नंबर",
        "ईमेल आईडी",
      ],
    },
  },
  {
    id: "partnership-deed",
    iconName: "FileText",
    category: "OTHER",
    title: {
      EN: "Partnership Deed",
      GU: "ભાગીદારી દસ્તાવેજ",
      HI: "पार्टनरशिप डीड",
    },
    description: {
      EN: "Documents required for preparing a partnership deed.",
      GU: "ભાગીદારી દસ્તાવેજ (Partnership Deed) બનાવવા માટેના પુરાવા.",
      HI: "पार्टनरशिप डीड तैयार करने हेतु आवश्यक दस्तावेज़।",
    },
    documents: {
      EN: [
        "1 photo of each partner",
        "Aadhaar Card of each partner",
        "PAN Card of each partner",
        "Firm name and address",
        "Main nature of business",
        "Rent Agreement (if premises on rent)",
        "Share percentage of each partner",
      ],
      GU: [
        "દરેક ભાગીદારોના ફોટા - ૧",
        "દરેક ભાગીદારોના આધાર કાર્ડ",
        "દરેક ભાગીદારોના પાન કાર્ડ",
        "પેઢીનું નામ તથા સરનામું",
        "પેઢીનું મુખ્ય કામકાજ",
        "ભાડાની જગ્યા હોય તો ભાડા કરાર",
        "ભાગીદારોની ટકાવારી",
      ],
      HI: [
        "प्रत्येक भागीदार का 1 फोटो",
        "प्रत्येक भागीदार का आधार कार्ड",
        "प्रत्येक भागीदार का पैन कार्ड",
        "फर्म का नाम और पता",
        "फर्म का मुख्य व्यवसाय",
        "यदि जगह किराये की हो तो रेंट एग्रीमेंट",
        "प्रत्येक भागीदार की प्रतिशत हिस्सेदारी",
      ],
    },
  },
  {
    id: "passport",
    iconName: "FileText",
    category: "ONLINE",
    title: {
      EN: "Passport",
      GU: "પાસપોર્ટ",
      HI: "पासपोर्ट",
    },
    description: {
      EN: "Documents required for applying for a passport.",
      GU: "પાસપોર્ટ માટે અરજી કરવા જરૂરી દસ્તાવેજો.",
      HI: "पासपोर्ट के लिए आवेदन हेतु आवश्यक दस्तावेज़।",
    },
    documents: {
      EN: [
        "Aadhaar Card",
        "Voter ID Card",
        "PAN Card",
        "Leaving Certificate or Birth Certificate",
        "Last Marksheet",
        "Marriage Certificate (if married)",
        "Mobile Number",
        "Email ID",
        "Emergency contact person's name and mobile number",
      ],
      GU: [
        "આધાર કાર્ડ",
        "ચુંટણી કાર્ડ",
        "પાન કાર્ડ",
        "લિવિંગ સર્ટીફીકેટ અથવા જન્મ નો દાખલો",
        "લાસ્ટ માર્કશીટ",
        "મેરેજ સર્ટીફીકેટ (મેરેજ થયેલ હોય તો)",
        "મોબાઈલ નંબર",
        "ઈ મેઈલ ID",
        "ઈમરજન્સી કોન્ટેકટ પર્સન નું નામ અને મોબાઈલ નંબર",
      ],
      HI: [
        "आधार कार्ड",
        "वोटर आईडी कार्ड",
        "पैन कार्ड",
        "लिविंग सर्टिफिकेट या जन्म प्रमाण पत्र",
        "अंतिम कक्षा की मार्कशीट",
        "विवाह प्रमाण पत्र (यदि विवाहित हों)",
        "मोबाइल नंबर",
        "ईमेल आईडी",
        "इमरजेंसी कॉन्टैक्ट व्यक्ति का नाम और मोबाइल नंबर",
      ],
    },
  },
  {
    id: "rent-agreement",
    iconName: "FileText",
    category: "OTHER",
    title: {
      EN: "Rent Agreement",
      GU: "ભાડા કરાર",
      HI: "रेंट एग्रीमेंट",
    },
    description: {
      EN: "Documents required for preparing a rent agreement.",
      GU: "ભાડા કરાર (Rent Agreement) બનાવવા માટેના પુરાવા.",
      HI: "रेंट एग्रीमेंट तैयार करने हेतु आवश्यक दस्तावेज़।",
    },
    documents: {
      EN: [
        "1 photo of owner (landlord)",
        "Aadhaar Card of owner",
        "1 photo of tenant",
        "Aadhaar Card of tenant",
        "Electricity Bill",
        "Property Tax Bill",
        "Copy of property documents",
      ],
      GU: [
        "ભાડે આ૫નાર (માલીક) નો ફોટો - ૧",
        "ભાડે આ૫નાર (માલીક) નું આધાર કાર્ડ",
        "ભાડે રાખનાર (ભાડુઆત) નો ફોટો - ૧",
        "ભાડે રાખનાર (ભાડુઆત) નું આધાર કાર્ડ",
        "લાઇટ બીલ",
        "વેરા બીલ",
        "દસ્તાવેજની નકલ",
      ],
      HI: [
        "मकान मालिक का 1 फोटो",
        "मकान मालिक का आधार कार्ड",
        "किरायेदार का 1 फोटो",
        "किरायेदार का आधार कार्ड",
        "बिजली बिल",
        "प्रॉपर्टी टैक्स बिल",
        "प्रॉपर्टी दस्तावेज़ की नकल",
      ],
    },
  },
  {
    id: "new-ration-card-division",
    iconName: "FileText",
    category: "OTHER",
    title: {
      EN: "New Ration Card (After Division)",
      GU: "નવું રેશન કાર્ડ (વિભાજનથી)",
      HI: "नया राशन कार्ड (विभाजन से)",
    },
    description: {
      EN: "Documents for obtaining a new ration card after family division.",
      GU: "વિભાગ બાદ નવું રેશન કાર્ડ મેળવવા માટે જરૂરી દસ્તાવેજો.",
      HI: "परिवार विभाजन के बाद नया राशन कार्ड लेने हेतु दस्तावेज़।",
    },
    documents: {
      EN: [
        "Existing Ration Card",
        "2 photos",
        "Aadhaar Card of all family members",
        "Voter ID Cards (if available)",
        "Applicant's Bank Passbook",
        "Applicant's Income Certificate",
        "Electricity Bill",
        "Property Tax Bill",
      ],
      GU: [
        "રેશન કાર્ડ",
        "૨ ફોટા",
        "આધાર કાર્ડ તમામ સભ્યો ના",
        "ચુંટણી કાર્ડ (હોય તેના)",
        "અરજદાર ની બેંક પાસબૂક",
        "અરજદારનો આવકનો દાખલો",
        "લાઇટબીલ",
        "વેરાબીલ",
      ],
      HI: [
        "पुराना राशन कार्ड",
        "2 फोटो",
        "सभी सदस्यों के आधार कार्ड",
        "वोटर आईडी कार्ड (यदि हो)",
        "आवेदक की बैंक पासबुक",
        "आवेदक का आय प्रमाण पत्र",
        "बिजली बिल",
        "प्रॉपर्टी टैक्स बिल",
      ],
    },
  },
  {
    id: "senior-citizen-cert",
    iconName: "FileText",
    category: "CERTIFICATE",
    title: {
      EN: "Senior Citizen Certificate",
      GU: "સીનીયર સીટીઝન પ્રમાણપત્ર",
      HI: "सीनियर सिटिजन प्रमाण पत्र",
    },
    description: {
      EN: "Certificate for recognition as a senior citizen.",
      GU: "વરિષ્ઠ નાગરિક તરીકે માન્યતા માટેનું પ્રમાણપત્ર.",
      HI: "वरिष्ठ नागरिक के रूप में मान्यता के लिए प्रमाण पत्र।",
    },
    documents: {
      EN: [
        "Photo of applicant",
        "Aadhaar Card",
        "Voter ID Card",
        "Ration Card",
        "Electricity Bill",
        "Property Tax Bill",
        "Applicant's Leaving Certificate or Birth Certificate",
      ],
      GU: [
        "ફોટો અરજદાર નો",
        "આધાર કાર્ડ",
        "ચુંટણી કાર્ડ",
        "રેશન કાર્ડ",
        "લાઇટબીલ",
        "વેરાબીલ",
        "અરજદાર નું લીવિંગ સર્ટી અથવા જન્મ નો દાખલો",
      ],
      HI: [
        "आवेदक का फोटो",
        "आधार कार्ड",
        "वोटर आईडी कार्ड",
        "राशन कार्ड",
        "बिजली बिल",
        "प्रॉपर्टी टैक्स बिल",
        "आवेदक का लिविंग सर्टिफिकेट या जन्म प्रमाण पत्र",
      ],
    },
  },
  {
    id: "udyog-aadhaar",
    iconName: "FileText",
    category: "ONLINE",
    title: {
      EN: "Udyog Aadhaar / Business Registration",
      GU: "ઉદ્યોગ આધાર નોંધણી",
      HI: "उद्योग आधार / व्यवसाय पंजीकरण",
    },
    description: {
      EN: "Documents required for Udyog Aadhaar or small business registration.",
      GU: "ઉદ્યોગ આધાર અથવા નાના ધંધાની નોંધણી માટે જરૂરી દસ્તાવેજો.",
      HI: "उद्योग आधार या छोटे व्यवसाय पंजीकरण हेतु दस्तावेज़।",
    },
    documents: {
      EN: [
        "Aadhaar Card",
        "PAN Card",
        "Bank Passbook",
        "Business name and address",
        "Business start date",
        "Mobile Number",
        "Email ID",
      ],
      GU: [
        "આધાર કાર્ડ",
        "પાન કાર્ડ",
        "બેંક પાસબૂક",
        "ધંધા નુ નામ સરનામું",
        "ધંધો શરૂ કર્યા ની તારીખ",
        "મોબાઈલ નંબર",
        "ઈ મેઈલ ID",
      ],
      HI: [
        "आधार कार्ड",
        "पैन कार्ड",
        "बैंक पासबुक",
        "व्यवसाय का नाम और पता",
        "व्यवसाय शुरू करने की तारीख",
        "मोबाइल नंबर",
        "ईमेल आईडी",
      ],
    },
  },
  {
    id: "heirship-certificate",
    iconName: "FileText",
    category: "CERTIFICATE",
    title: {
      EN: "Heirship / Succession Certificate",
      GU: "વારસાઈ આંબો",
      HI: "वारसाई / उत्तराधिकार प्रमाण पत्र",
    },
    description: {
      EN: "Documents required for heirship / succession certificate.",
      GU: "વારસાઈ આંબા માટે જરૂરી દસ્તાવેજો.",
      HI: "वारसाई / उत्तराधिकार प्रमाण पत्र हेतु आवश्यक दस्तावेज़।",
    },
    documents: {
      EN: [
        "2 photos (of any one heir in case of death)",
        "Aadhaar Card of applicant (if alive)",
        "Ration Card of applicant",
        "Aadhaar Cards of all heirs (sons/daughters, husband/wife)",
        "Death Certificate (in case of death)",
        "Other relevant documents if any",
      ],
      GU: [
        "૨ ફોટા (મરણ ના કિસ્સા માં કોઈ એક વારસદાર ના ફોટા)",
        "આધાર કાર્ડ અરજદાર નું (હૈયાતી માં હોય તો)",
        "રેશન કાર્ડ અરજદારનું",
        "અરજદાર ના વારસદારો પુત્ર/પુત્રી, પતિ/પತ್ನી ના આધાર કાર્ડ",
        "મરણ ના કિસ્સા માં મરણ નોંધ નો દાખલો",
      ],
      HI: [
        "2 फोटो (मृत्यु के मामले में किसी एक वारिस के)",
        "आवेदक का आधार कार्ड (यदि जीवित हों)",
        "आवेदक का राशन कार्ड",
        "सभी वारिसों (पुत्र/पुत्री, पति/पत्नी) के आधार कार्ड",
        "मृत्यु के मामले में मृत्यु प्रमाण पत्र",
      ],
    },
  },
  {
    id: "vahali-dikri-yojana",
    iconName: "FileText",
    category: "ASSISTANCE",
    title: {
      EN: "Vahali Dikri Yojana",
      GU: "વ્હાલી દીકરી યોજના",
      HI: "वहाली बेटी योजना",
    },
    description: {
      EN: "Documents required for Vahali Dikri Yojana assistance for daughters.",
      GU: "વ્હાલી દીકરી સહાય યોજના માટે જરૂરી દસ્તાવેજો.",
      HI: "वहाली बेटी योजना के लिए आवश्यक दस्तावेज़।",
    },
    documents: {
      EN: [
        "1 photo of daughter and 1 photo of parents",
        "Aadhaar Card of daughter and parents",
        "Birth Certificate of daughter",
        "Ration Card",
        "Income Certificate of father",
        "Bank Passbook of daughter (SBI / BOB / UNION / CBI)",
        "Electricity Bill",
        "Marriage Registration Certificate of parents",
        "Leaving / Birth Certificates of parents",
        "Birth Certificate and Aadhaar Card of second child (if any)",
        "Note: Form must be filled within 1 year of daughter's birth",
      ],
      GU: [
        "૧ ફોટા દીકરી તથા માતા / પિતાના ૧-૧ ફોટા",
        "આધાર કાર્ડ દીકરી નું તથા માતા / પિતા નું",
        "દીકરી નો જન્મ નો દાખલો",
        "રેશન કાર્ડ",
        "આવક નો દાખલો પિતાનો",
        "બેંક પાસબૂક (S.B.I ./  B.O.B./  UNION / C.B.I)",
        "લાઇટબીલ",
        "લગ્ન નોંધ નું પ્રમાણપત્ર",
        "માતા / પિતાના લીવીંગ અથવા જન્મ ના દાખલા",
        "બીજું સંતાન હોય તો તેનો જન્મ નો દાખલો તથા આધાર કાર્ડ",
        "નોંધ: દીકરી ના જન્મ ના ૧ વર્ષ ની સમય મર્યાદામાં ફોર્મ ભરવાનું રહેશે.",
      ],
      HI: [
        "1 फोटो बेटी का और माता–पिता के 1–1 फोटो",
        "बेटी और माता–पिता के आधार कार्ड",
        "बेटी का जन्म प्रमाण पत्र",
        "राशन कार्ड",
        "पिता का आय प्रमाण पत्र",
        "बेटी की बैंक पासबुक (SBI / BOB / UNION / CBI)",
        "बिजली बिल",
        "माता–पिता का विवाह पंजीकरण प्रमाण पत्र",
        "माता–पिता के लिविंग या जन्म प्रमाण पत्र",
        "दूसरा संतान हो तो उसका जन्म प्रमाण पत्र और आधार कार्ड",
        "नोट: बेटी के जन्म से 1 वर्ष के अंदर फॉर्म भरना अनिवार्य है।",
      ],
    },
  },
  {
    id: "widow-assistance-scheme",
    iconName: "FileText",
    category: "ASSISTANCE",
    title: {
      EN: "Widow Assistance Scheme",
      GU: "વિધવા સહાય યોજના",
      HI: "विधवा सहायता योजना",
    },
    description: {
      EN: "Documents required for widow assistance scheme.",
      GU: "વિધવા સહાય યોજના માટે જરૂરી દસ્તાવેજો.",
      HI: "विधवा सहायता योजना हेतु आवश्यक दस्तावेज़।",
    },
    documents: {
      EN: [
        "4 photos",
        "Aadhaar Card of applicant",
        "Ration Card of applicant",
        "Income Certificate of applicant",
        "Bank Passbook of applicant (SBI / BOB / UNION / CBI)",
        "Electricity Bill",
        "Property Tax Bill",
        "Death Certificate of husband",
        "Aadhaar Cards of all heirs (sons/daughters)",
        "If heirs have separate ration card: their ration card and income certificate",
      ],
      GU: [
        "૪ ફોટા",
        "આધાર કાર્ડ અરજદાર નું",
        "રેશન કાર્ડ અરજદારનું",
        "અરજદાર નો આવક નો દાખલો",
        "અરજદાર ની બેંક પાસબૂક (S.B.I./ B.O.B./ UNION / C.B.I.)",
        "લાઇટબીલ",
        "વેરાબીલ",
        "મરણ નોંધ નો દાખલો",
        "બધા વારસદારો ના આધાર કાર્ડ પુત્ર / પુત્રી બંને",
        "વારસદાર નું રેશન કાર્ડ અલગ હોય તો તેમનું રેશન કાર્ડ અને આવક નો દાખલો",
      ],
      HI: [
        "4 फोटो",
        "आवेदक (विधवा) का आधार कार्ड",
        "आवेदक का राशन कार्ड",
        "आवेदक का आय प्रमाण पत्र",
        "आवेदक की बैंक पासबुक (SBI / BOB / UNION / CBI)",
        "बिजली बिल",
        "प्रॉपर्टी टैक्स बिल",
        "पति का मृत्यु प्रमाण पत्र",
        "सभी वारिसों (पुत्र/पुत्री) के आधार कार्ड",
        "यदि वारिसों का राशन कार्ड अलग हो तो उनका राशन कार्ड व आय प्रमाण पत्र",
      ],
    },
  },

  {
    id: "pandit-deendayal-awas-yojana",
    iconName: "FileText",
    category: "ASSISTANCE",
    title: {
      EN: "Pandit Deendayal Awas Yojana",
      GU: "પંડીત દીન દયાળ આવાસ યોજના",
      HI: "पंडित दीनदयाल आवास योजना",
    },
    description: {
      EN: "Documents required for Pandit Deendayal Awas Housing Assistance Scheme.",
      GU: "પંડીત દીન દયાળ આવાસ સહાય યોજના માટે જરૂરી દસ્તાવેજો.",
      HI: "पंडित दीनदयाल आवास सहायता योजना हेतु आवश्यक दस्तावेज़।",
    },
    documents: {
      EN: [
        "Applicant's caste/sub-caste certificate (Not required for economically backward applicants)",
        "Applicant’s Leaving Certificate (if educated)",
        "Income Certificate",
        "Residential proof (Aadhaar Card / Electricity Bill / Driving License / Rent Agreement / Voter ID / Ration Card – any one)",
        "Allotment order copy if land/house was received in any poverty housing scheme",
        "Land ownership documents (Akarni Patrak / Hak Patrak / Sanad)",
        "Certificate from Talati / City Talati / Circle Inspector for house assistance approval",
        "House construction permission letter",
        "BPL Card",
        "Husband's Death Certificate (if widow)",
        "Signed map showing land boundaries (Talati-certified)",
        "Bank Passbook / Cancelled Cheque",
        "Applicant's Photo",
      ],
      GU: [
        "અરજદારની જાતિ/પેટા જાતિનો દાખલો (આર્થિક પછાતવર્ગ માટે ફરજીયાત નથી)",
        "અરજદારનું લીવીંગ સર્ટીફીકેટ (શિક્ષિત હોય તો)",
        "આવકનો દાખલો",
        "અરજદારનો રહેઠાણનો પુરાવો (આધાર કાર્ડ/ વીજળી બિલ/ લાઇસન્સ/ ભાડાકરાર/ ચુંટણી કાર્ડ/ રેશન કાર્ડ પૈકી કોઈપણ એક)",
        "કોઈ ગરીબી આવાસ યોજના હેઠળ મળેલ જમીન/મકાનના ફાળવણી હુકમની નકલ",
        "જમીન માલિકીનું આધાર/દસ્તાવેજ/અકારની પત્રક/હક પત્રક/સનદ પત્રક",
        "મકાન સહાય માટે તલાટી/સિટી તલાટી/સર્કલ ઇન્સ્પેક્ટરનું પ્રમાણપત્ર",
        "મકાન બાંધકામ કરવાની રજા ચિઠ્ઠી",
        "BPLનો દાખલો",
        "પતિના મરણ નો દાખલો (વિધવા માટે)",
        "જમીનના ક્ષેત્રફળ અને ચતુર્દિશા દર્શાવતો નકશો (તલાટી સહીવાળો)",
        "પાસબુક / કેન્સલ ચેક",
        "અરજદારના ફોટો",
      ],
      HI: [
        "आवेदक की जाति/उपजाति प्रमाण पत्र (आर्थिक पिछड़ा वर्ग के लिए आवश्यक नहीं)",
        "आवेदक का लीविंग सर्टिफिकेट (यदि शिक्षित हो)",
        "आय प्रमाण पत्र",
        "निवास प्रमाण (आधार कार्ड / बिजली बिल / लाइसेंस / किरायानामा / वोटर आईडी / राशन कार्ड – कोई एक)",
        "यदि किसी आवास योजना में भूमि/मकान मिला हो तो उसका आवंटन पत्र",
        "भूमि स्वामित्व दस्तावेज़ (अकारणी पत्रक / हक पत्रक / सनद)",
        "तलाठी / सिटी तलाठी / सर्कल इंस्पेक्टर का प्रमाण पत्र",
        "मकान निर्माण अनुमति पत्र",
        "BPL कार्ड",
        "पति का मृत्यु प्रमाण पत्र (यदि विधवा)",
        "भूमि की सीमाएं दर्शाता नक्शा (तलाठी हस्ताक्षरित)",
        "पासबुक / कैंसल चेक",
        "आवेदक का फोटो",
      ],
    },
  },

  {
    id: "foster-parents-documents",
    iconName: "FileText",
    category: "ASSISTANCE",
    title: {
      EN: "Foster Parents Yojana",
      GU: "પાલક માતા-પિતા યોજના ",
      HI: "पालक माता–पिता हेतु आवश्यक दस्तावेज़",
    },
    description: {
      EN: "Documents required for Foster Parents Registration.",
      GU: "પાલક માતા-પિતા નોંધણી માટે જરૂરી દસ્તાવેજો.",
      HI: "पालक माता–पिता पंजीकरण के लिए आवश्यक दस्तावेज़।",
    },
    documents: {
      EN: [
        "Child's Birth Certificate",
        "Child's Aadhaar Card (copy)",
        "Child's School Bonafide Certificate",
        "Death Certificates and Aadhaar Cards of biological parents",
        "Child's single photo",
        "Child's joint photo with foster parents",
        "Child’s Bank Passbook with foster parents (joint)",
        "Foster parents' coupon copy",
        "Foster parents' Aadhaar Card copies",
        "Income Certificate of foster father",
        "Electricity Bill copy",
      ],
      GU: [
        "બાળકનો જન્મ દાખલો",
        "બાળકનુ આધાર કાર્ડ ની ઝેરોક્ષ",
        "બાળકનું સ્કુલ બોનાફાઇડ",
        "બાળકના માતા પીતાના મરણ દાખલા તથા આધાર કાર્ડ",
        "બાળકનો સિંગલ ફોટો",
        "બાળકનો ફોટો પાલક માતા પીતા સાથે જોઇન્ટમાં",
        "બાળકની બેન્ક પાસબુક પાલક માતા પીતા સાથે જોઇન્ટમાં",
        "પાલક માતા-પિતા કુપનની ઝેરોક્ષ",
        "પાલક માતા પીતા આધાર કાર્ડ ની ઝેરોક્ષ",
        "પાલક પીતા નો આવક દાખલો",
        "લાઇટ બિલ ની ઝેરોક્ષ",
      ],
      HI: [
        "बच्चे का जन्म प्रमाण पत्र",
        "बच्चे का आधार कार्ड (कॉपी)",
        "बच्चे का स्कूल बोनाफाइड",
        "बच्चे के माता–पिता के मृत्यु प्रमाण पत्र व आधार कार्ड",
        "बच्चे का एकल फोटो",
        "बच्चे का पालक माता–पिता के साथ संयुक्त फोटो",
        "बच्चे की बैंक पासबुक (पालक माता–पिता के साथ संयुक्त)",
        "पालक माता–पिता के कूपन की कॉपी",
        "पालक माता–पिता के आधार कार्ड की कॉपी",
        "पालक पिता का आय प्रमाण पत्र",
        "बिजली बिल की कॉपी",
      ],
    },
  },

  {
    id: "home-loan-subsidy",
    iconName: "FileText",
    category: "ONLINE",
    title: {
      EN: "Home Loan Subsidy",
      GU: "હોમ લોન સબસીડી",
      HI: "होम लोन सब्सिडी दस्तावेज़",
    },
    description: {
      EN: "Documents required to apply for Home Loan Subsidy.",
      GU: "હોમ લોનની સબસીડી મેળવવા માટે જરૂરી દસ્તાવેજો.",
      HI: "होम लोन सब्सिडी हेतु आवश्यक दस्तावेज़।",
    },
    documents: {
      EN: [
        "Aadhaar Card",
        "PAN Card",
        "Ration Card and Aadhaar Cards of all listed members",
        "Aadhaar Cards of parents (of applicant)",
        "Loan documents from bank",
        "ITR or Income Certificate",
        "Loan Account Number",
        "Property Value Document",
        "Loan Sanction Date",
        "Loan Disbursement Date",
      ],
      GU: [
        "આધારકાર્ડ",
        "પાનકાર્ડ",
        "રાશન કાર્ડ અને તેમાં નામ હોય તે બધાના આધાર કાર્ડ",
        "જેનું ફોર્મ ભરવાનું હોય તેના માતા-પિતાના આધાર કાર્ડ",
        "લોનના ડોક્યુમેન્ટ (બેન્ક તરફથી)",
        "આઇટી રિટર્ન અથવા આવકનો દાખલો",
        "લોન એકાઉન્ટ નંબર",
        "પ્રોપર્ટીની વેલ્યુ",
        "લોન સેંક્શન તારીખ",
        "લોન ડિસબર્સમેન્ટ તારીખ",
      ],
      HI: [
        "आधार कार्ड",
        "पैन कार्ड",
        "राशन कार्ड और उसमें नामित सभी सदस्यों के आधार कार्ड",
        "आवेदक के माता–पिता के आधार कार्ड",
        "बैंक द्वारा दिए गए लोन दस्तावेज़",
        "आईटीआर या आय प्रमाण पत्र",
        "लोन अकाउंट नंबर",
        "प्रॉपर्टी वैल्यू दस्तावेज़",
        "लोन स्वीकृति तिथि",
        "लोन वितरण (डिसबर्समेंट) तिथि",
      ],
    },
  },

  {
    id: "vimukta-jati-certificate",
    iconName: "FileText",
    category: "CERTIFICATE",
    title: {
      EN: "Vimukta Jati / Nomadic Tribe Certificate",
      GU: "વિચરતી–વિમુકત જાતિનો દાખલો",
      HI: "विचरती–विमुक्त जाति प्रमाण पत्र",
    },
    description: {
      EN: "Documents required for obtaining Vimukta Jati / Nomadic Tribe Certificate.",
      GU: "વિચરતી–વિમુકત જાતિના દાખલા મેળવવા માટે જરૂરી દસ્તાવેજો.",
      HI: "विचरती–विमुक्त जाति प्रमाण पत्र प्राप्त करने हेतु आवश्यक दस्तावेज़।",
    },
    documents: {
      EN: [
        "1 photo of applicant and 1 photo of father",
        "Aadhaar Card and Voter ID of applicant and father",
        "Applicant's Leaving Certificate or Bonafide Certificate",
        "Leaving Certificate of father / uncle / aunt (any one)",
        "Ration Card",
        "Income Certificate",
        "Applicant's caste certificate of social and educational category",
        "Electricity Bill",
        "Property Tax Bill",
      ],
      GU: [
        "(૧) ફોટો અરજદાર નો અને (૧) ફોટો તેના પિતા નો",
        "આધાર કાર્ડ અને ચુટણી કાર્ડ (અરજદાર અને તેના પિતા નુ)",
        "અરજદાર નું લિવિંગ સર્ટી અથવા બોનાફાઇડ",
        "આવક નો દાખલો",
        "અરજદાર નો સામાજિક અને શૈક્ષણિક વર્ગનો જાતી દાખલો",
        "અરજદાર ના પિતા/કાકા/ફોઈ કોઈ એક નું લિવિંગ સર્ટી",
        "રેશન કાર્ડ",
        "લાઇટબીલ",
        "વેરાબીલ",
      ],
      HI: [
        "1 फोटो आवेदक का और 1 फोटो उसके पिता का",
        "आधार कार्ड और वोटर आईडी (आवेदक और पिता का)",
        "आवेदक का लीविंग सर्टिफिकेट या बोनाफाइड",
        "आवेदक के पिता / काका / बुआ में से किसी एक का लीविंग सर्टिफिकेट",
        "राशन कार्ड",
        "बिजली बिल",
        "प्रॉपर्टी टैक्स बिल",
      ],
    },
  },

  {
    id: "religious-minority-certificate",
    iconName: "FileText",
    category: "CERTIFICATE",
    title: {
      EN: "Religious Minority Certificate",
      GU: "ધાર્મિક લઘુમતીનો દાખલો",
      HI: "धार्मिक अल्पसंख्यक प्रमाण पत्र",
    },
    description: {
      EN: "Certificate for applicants belonging to a recognized religious minority community.",
      GU: "ધાર્મિક લઘુમતી સમુદાયમાં આવનારા અરજદારો માટેનું પ્રમાણપત્ર.",
      HI: "मान्यता प्राप्त धार्मिक अल्पसंख्यक समुदाय से संबंधित आवेदकों के लिए प्रमाण पत्र।",
    },
    documents: {
      EN: [
        "1 photo of applicant and 1 photo of father",
        "Aadhaar Card and Voter ID (of applicant and father)",
        "Applicant's Leaving Certificate or Bonafide Certificate",
        "Leaving Certificate of father / uncle / aunt (any one)",
        "Ration Card",
        "Income Certificate",
        "Electricity Bill",
        "Property Tax Bill",
        "Certificate from community/religious leader (Samaj Pramukh)",
      ],
      GU: [
        "(૧) ફોટો અરજદાર નો અને (૧) ફોટો તેના પિતા નો",
        "આધાર કાર્ડ અને ચુટણી કાર્ડ (અરજદાર અને તેના પિતા નુ)",
        "અરજદાર નું લિવિંગ સર્ટી અથવા બોનાફાઇડ",
        "અરજદાર ના પિતા/કાકા/ફોઈ માંથી કોઈ એકનું લિવિંગ સર્ટી",
        "રેશન કાર્ડ",
        "લાઇટબીલ",
        "વેરાબીલ",
        "આવક નો દાખલો",
        "જ્ઞાતિના પ્રમુખ નો દાખલો",
      ],
      HI: [
        "1 फोटो आवेदक का और 1 फोटो उसके पिता का",
        "आधार कार्ड और वोटर आईडी (आवेदक और पिता का)",
        "आवेदक का लिविंग सर्टिफिकेट या बोनाफाइड",
        "आवेदक के पिता / काका / बुआ में से किसी एक का लिविंग सर्टिफिकेट",
        "राशन कार्ड",
        "बिजली बिल",
        "प्रॉपर्टी टैक्स बिल",
        "समाज/धार्मिक प्रमुख का प्रमाण पत्र",
      ],
    },
  },

  {
    id: "scholarship-documents",
    iconName: "FileText",
    category: "ONLINE",
    title: {
      EN: "Digital Scholarship ",
      GU: "ડિજિટલ સ્કોલરશીપ",
      HI: "स्कॉलरशिप हेतु आवश्यक दस्तावेज़",
    },
    description: {
      EN: "Documents required for applying to scholarship schemes for students.",
      GU: "વિદ્યાર્થીઓ માટેની સ્કોલરશીપ યોજનામાં અરજી કરવા જરૂરી દસ્તાવેજો.",
      HI: "छात्रों द्वारा स्कॉलरशिप आवेदन हेतु आवश्यक दस्तावेज़।",
    },
    documents: {
      EN: [
        "Student's Aadhaar Card",
        "Student's Bank Passbook",
        "All academic mark sheets",
        "Caste Certificate of student",
        "School Leaving Certificate",
        "School/College Bonafide Certificate",
        "Parent's Income Certificate",
        "Student's photo",
        "Hostel fee receipt (if applicable)",
        "School/college fee payment receipt",
        "Gap Certificate (if study gap exceeds 1 year)",
      ],
      GU: [
        "વિદ્યાર્થીનું આધાર કાર્ડ",
        "વિદ્યાર્થીની બેંક પાસબુક",
        "અભ્યાસની તમામ માર્કશીટ",
        "વિદ્યાર્થીનો જ્ઞાતિનો દાખલો",
        "સ્કુલ લીવીંગ સર્ટીફીકેટ",
        "સ્કુલ/કોલેજ બોનાફાઈડ સર્ટીફીકેટ",
        "વાલીનો આવકનો દાખલો",
        "વિદ્યાર્થીનો ફોટો",
        "હોસ્ટેલફીની પહોચ (લાગુ પડતું હોય તો)",
        "સ્કુલ-કોલેજ ફી ભર્યાની પહોચ",
        "ગેપ સર્ટીફીકેટ (1 વર્ષથી વધુ ગેપ હોય તો)",
      ],
      HI: [
        "छात्र का आधार कार्ड",
        "छात्र की बैंक पासबुक",
        "सभी शैक्षणिक मार्कशीट",
        "छात्र का जाति प्रमाण पत्र",
        "स्कूल लीविंग सर्टिफिकेट",
        "स्कूल/कॉलेज बोनाफाइड सर्टिफिकेट",
        "अभिभावक का आय प्रमाण पत्र",
        "छात्र का फोटो",
        "होस्टल शुल्क रसीद (यदि लागू हो)",
        "स्कूल/कॉलेज फीस रसीद",
        "गैप सर्टिफिकेट (यदि 1 वर्ष से अधिक का अंतर हो)",
      ],
    },
  },

  {
    id: "old-age-pension-scheme",
    iconName: "FileText",
    category: "ASSISTANCE",
    title: {
      EN: "Old Age Pension Scheme",
      GU: "વૃદ્ધ પેન્શન યોજના",
      HI: "वृद्ध पेंशन योजना",
    },
    description: {
      EN: "Documents required for old age pension scheme (for senior citizens above 60 years).",
      GU: "૬૦ વર્ષથી ઉપર વય ધરાવતા વરિષ્ઠ નાગરિકો માટે વૃદ્ધ પેન્શન યોજના માટેના દસ્તાવેજો.",
      HI: "60 वर्ष से अधिक आयु के वरिष्ठ नागरिकों के लिए वृद्ध पेंशन योजना हेतु दस्तावेज़।",
    },
    documents: {
      EN: [
        "Applicant must be above 60 years of age",
        "2 photos",
        "Aadhaar Card of applicant",
        "Ration Card of applicant",
        "Voter ID Card",
        "Income Certificate",
        "Bank Passbook of applicant (SBI / BOB / UNION / CBI)",
        "Electricity Bill and Property Tax Bill",
        "Leaving Certificate or Age Certificate from Government Hospital",
        "BPL Card",
        "Note: Scheme available only for BPL card holders and those without a son; heirship certificate in such case",
      ],
      GU: [
        "અરજદારની ઉંમર ૬૦ વર્ષથી ઉપર હોય તો અરજી કરી શકાશે.",
        "૨ ફોટા",
        "આધાર કાર્ડ અરજદાર નું",
        "રેશન કાર્ડ અરજદારનું",
        "ચુંટણી કાર્ડ",
        "આવક નો દાખલો",
        "અરજદાર ની બેંક પાસબૂક (S.B.I./ B.O.B./ UNION / C.B.I.)",
        "લાઇટબીલ અને વેરાબીલ",
        "લીવિંગ સર્ટીફીકેટ અથવા સરકારી હોસ્પિટલ થી ઉંમર નો દાખલો",
        "BPL કાર્ડ",
        "નોંધ: આ યોજના માત્ર BPL કાર્ડ ધારકો અને પુત્ર ન હોય તેવા અરજદારો માટે જ ઉપલબ્ધ છે; આવા કિસ્સામાં વારસાઈ આંબો જરૂરી.",
      ],
      HI: [
        "आवेदक की आयु 60 वर्ष से अधिक होनी चाहिए।",
        "2 फोटो",
        "आवेदक का आधार कार्ड",
        "आवेदक का राशन कार्ड",
        "वोटर आईडी कार्ड",
        "आय प्रमाण पत्र",
        "आवेदक की बैंक पासबुक (SBI / BOB / UNION / CBI)",
        "बिजली बिल और प्रॉपर्टी टैक्स बिल",
        "सरकारी अस्पताल से लिविंग सर्टिफिकेट या आयु प्रमाण पत्र",
        "BPL कार्ड",
        "नोट: यह योजना केवल BPL कार्ड धारकों और जिनके पुत्र नहीं हैं उनके लिए उपलब्ध है; ऐसे मामलों में वारसाई प्रमाण पत्र आवश्यक है।",
      ],
    },
  },
];

export const TESTIMONIALS_DATA = [
  {
    id: 1,
    name: "Rajesh Patel",
    role: "Business Owner",
    rating: 5,
    content: {
      EN: "Excellent service! Got my Udyog Aadhar within 30 minutes  without any hassle.",
      GU: "ઉત્કૃષ્ટ સેવા! કોઈ મુશ્કેલી વિના 30 મિનિટ મારો ઉદ્યોગ આધાર મળ્યો.",
      HI: "उत्कृष्ट सेवा! बिना किसी परेशानी के 2 दिनों के भीतर मेरा उद्योग आधार मिल गया।",
    },
  },
  {
    id: 2,
    name: "Vinit Karshala",
    role: "Student",
    rating: 5,
    content: {
      EN: "Applying for the Non-Creamy Layer certificate was so easy with Pragalbh Services.",
      GU: "પ્રગલ્ભ સેવાઓ સાથે નોન-ક્રીમી લેયર પ્રમાણપત્ર માટે અરજી કરવી ખૂબ જ સરળ હતી.",
      HI: "प्रगल्भ सर्विसेज के साथ नॉन-क्रीमी लेयर सर्टिफिकेट के लिए आवेदन करना बहुत आसान था।",
    },
  },
  {
    id: 3,
    name: "Amit Kumar",
    role: "Private Employee",
    rating: 4,
    content: {
      EN: "Very professional team. Guided me properly for my domicile certificate.",
      GU: "ખૂબ જ પ્રોફેશનલ ટીમ. મારા ડોમીસાઇલ પ્રમાણપત્ર માટે મને યોગ્ય માર્ગદર્શન આપ્યું.",
      HI: "बहुत ही पेशेवर टीम। मेरे मूल निवास प्रमाण पत्र के लिए मेरा सही मार्गदर्शन किया।",
    },
  },
];

// Dynamic Stats Calculation
const START_YEAR = 2015;
const CURRENT_YEAR = new Date().getFullYear();
const YEARS_EXPERIENCE = CURRENT_YEAR - START_YEAR;
const HAPPY_CLIENTS = YEARS_EXPERIENCE * 500;

export const STATS_DATA = [
  {
    id: 1,
    value: HAPPY_CLIENTS,
    suffix: "+",
    label: { EN: "Happy Clients", GU: "સંતુષ્ટ ગ્રાહકો", HI: "संतुष्ट ग्राहक" },
    iconName: "Users",
  },
  {
    id: 2,
    value: YEARS_EXPERIENCE,
    suffix: "+",
    label: {
      EN: "Years Experience",
      GU: "વર્ષોનો અનુભવ",
      HI: "वर्षों का अनुभव",
    },
    iconName: "Calendar",
  },
  {
    id: 3,
    value: SERVICES_DATA.length,
    suffix: "+",
    label: { EN: "Services Offered", GU: "ઉપલબ્ધ સેવાઓ", HI: "उपलब्ध सेवाएं" },
    iconName: "Briefcase",
  },
];
